version: '3'

services:
  messaging-client:
    image: syamsuldocker/messaging-client
    ports:
     - 80:80
     - 443:443
    # network_mode: "host"
    volumes: 
      - ./certbot/www:/var/www/certbot # ssl certificate
      - ./certbot/conf:/etc/nginx/ssl
    # environment:
    #   - DUMMY=1
    # env_file:
    # - /path/to/file
  