version: '3'

services:
  client:
    container_name: client
    hostname: client
    image: syamsuldocker/messaging-client
    volumes:
      - "./default.conf:/etc/nginx/conf.d/default.conf"
    network_mode: "host"
    
  
  